### ISSUE TITLE
Tracking issue: Edge support

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/opencast-studio#242]
The Edge browser currently only partially works:

- [x] Capture cameras via `getUserMedia`
- [ ] Capture screen via `getDisplayMedia`: available via `Navigator`, so we could poly fill. [caniuse](https://caniuse.com/#feat=mdn-api_mediadevices_getdisplaymedia)
- [ ] Record via `MediaRecorder`: "under consideration", [caniuse](https://caniuse.com/#feat=mediarecorder)

**Comment by LukasKalbertodt** [comment]
As far as I was able to test it, the new webkit-based version of Edge (79) solves all of this. Studio completely works.
